set_property IOSTANDARD LVCMOS33 [get_ports {r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {vs}]

set_property PACKAGE_PIN G17 [get_ports {r[3]}]
set_property PACKAGE_PIN G18 [get_ports {r[2]}]
set_property PACKAGE_PIN J15 [get_ports {r[1]}]
set_property PACKAGE_PIN H15 [get_ports {r[0]}]

set_property PACKAGE_PIN H17 [get_ports {g[3]}]
set_property PACKAGE_PIN H18 [get_ports {g[2]}]
set_property PACKAGE_PIN J22 [get_ports {g[1]}]
set_property PACKAGE_PIN H22 [get_ports {g[0]}]

set_property PACKAGE_PIN H20 [get_ports {b[3]}]
set_property PACKAGE_PIN G20 [get_ports {b[2]}]
set_property PACKAGE_PIN K21 [get_ports {b[1]}]
set_property PACKAGE_PIN K22 [get_ports {b[0]}]

set_property PACKAGE_PIN M21 [get_ports {hs}]
set_property PACKAGE_PIN L21 [get_ports {vs}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN P20 [get_ports rst]