# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/.vscode/Github/MIPS32_CPU/minisys/minisys.cache/wt [current_project]
set_property parent.project_path F:/.vscode/Github/MIPS32_CPU/minisys/minisys.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files F:/.vscode/Github/MIPS32_CPU/minisys/minisys.srcs/sources_1/ip/prgrom/prgmip32.coe
add_files F:/.vscode/Github/MIPS32_CPU/minisys/minisys.srcs/sources_1/ip/ram/dmem32.coe
add_files -quiet F:/.vscode/Github/MIPS32_CPU/minisys/minisys.runs/cpuclk_synth_1/cpuclk.dcp
set_property used_in_implementation false [get_files F:/.vscode/Github/MIPS32_CPU/minisys/minisys.runs/cpuclk_synth_1/cpuclk.dcp]
add_files -quiet F:/.vscode/Github/MIPS32_CPU/minisys/minisys.runs/prgrom_synth_1/prgrom.dcp
set_property used_in_implementation false [get_files F:/.vscode/Github/MIPS32_CPU/minisys/minisys.runs/prgrom_synth_1/prgrom.dcp]
add_files -quiet F:/.vscode/Github/MIPS32_CPU/minisys/minisys.runs/ram_synth_1/ram.dcp
set_property used_in_implementation false [get_files F:/.vscode/Github/MIPS32_CPU/minisys/minisys.runs/ram_synth_1/ram.dcp]
read_verilog -library xil_defaultlib {
  {F:/.vscode/Github/MIPS32_CPU/minisys/minisys.srcs/sources_1/imports/VGA char display/ram_set.v}
  {F:/.vscode/Github/MIPS32_CPU/minisys/minisys.srcs/sources_1/imports/VGA char display/vga_display.v}
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/switchs.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/memorio.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/leds.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/ioread.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/ifetc32.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/idecode32.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/executs32.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/dmemory32.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/control32.v
  F:/.vscode/Github/MIPS32_CPU/minisys/classfiles/minisys2.0/minisys.v
}
read_xdc F:/.vscode/Github/MIPS32_CPU/minisys/minisys.srcs/constrs_1/imports/xdc/minisys.xdc
set_property used_in_implementation false [get_files F:/.vscode/Github/MIPS32_CPU/minisys/minisys.srcs/constrs_1/imports/xdc/minisys.xdc]

synth_design -top minisys -part xc7a100tfgg484-1
write_checkpoint -noxdef minisys.dcp
catch { report_utilization -file minisys_utilization_synth.rpt -pb minisys_utilization_synth.pb }
